# Generated by Django 5.0.7 on 2024-08-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BANKS',
            fields=[
                ('Bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('inst_num', models.CharField(max_length=100)),
                ('swift_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BRANCHES',
            fields=[
                ('Branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('transit_num', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
            ],
        ),
    ]
