# Generated by Django 5.0.7 on 2024-08-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bank_branch_delete_banks_delete_branches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Bank_id',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='Branch_id',
            new_name='branch_id',
        ),
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
